yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
# без этой строки работать нймспэйс не будет(
app_name = 'posts'
# обращаемся чер <a class="nav..." href="{% url 'group_list' %}">
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<str:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    # Django проверяет url-адреса сверху вниз,
    # нам нужно, чтобы Django сначала проверял адреса в приложении users
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('group/', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    class Meta:
        ordering = ['-pub_date']
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    def __str__(self):
        # выводим текст поста
        return self.text

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea,
        label='Введите текст',
        required=True,
        help_text='Текст поста'
    )

    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {'group': 'Выберите группу'}
        help_texts = {
            'group': 'Группа поста'
        }

yatube/posts/views.py
# from django.http import HttpResponse
from .forms import PostForm
from django.core.paginator import Paginator
from .models import Post, Group, User
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
postsper: int = 10
# Главная страница
# @login_required


def paginator_func(posts, request):
    paginator = Paginator(posts, postsper)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    posts = Post.objects.all()
    page_obj = paginator_func(posts, request)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


# Групповая страница
def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()  # [:POST_COUNT]
    page_obj = paginator_func(posts, request)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    page_obj = paginator_func(posts, request)
    return render(request, 'posts/profile.html', {
        'page_obj': page_obj,
        'author': user,
    })


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    posts = get_object_or_404(Post, id=post_id)  # [:POST_COUNT]
    post_list = Post.objects.select_related('author').filter(
        author=posts.author)
    quantity = post_list.count()
    context = {
        'posts': posts,
        'quantity': quantity,
    }
    return render(request, template, context)


@login_required
def post_create(request):

    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(request.POST or None, instance=post)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
            'post_id': post_id,
            'is_edit': True
        })
    form.save()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
    
{% block title %}
  {% if is_edit %} Редактировать запись {% else %} Новый пост{% endif %}
{% endblock %}
{% block header %}
  {% if is_edit %}Редактировать запись{% else %}Создание нового поста{% endif %}
{% endblock %}
      
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %}
            </div>
            <div class="card-body">
                 
              <form method="POST" action="{% if is_edit %} {% url 'posts:post_edit' post_id=post_id %}{% else %}{% url 'posts:post_create' %}{% endif %}"  enctype="multipart/form-data" >
                
                {% csrf_token %}
                
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ field.label }}
                      {% if field.field.required %}
                        *
                      {% endif %}              
                    </label>
                    {{ field }}
                    {{ field.help_text }}
                  </div>
                {% endfor %}            
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}Сохранить {% else %}Добавить{% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}{{group.title}}{% endblock %}
{% block header %}<h1>{{group.title}}</h1>{% endblock %}
{% block content %}
<p>{{group.description|linebreaksbr}}</p>
  {% for post in page_obj %}
    <p>
        <ul>
          <li>Автор:<a href="{% url 'posts:profile' post.author.username %}">{{post.author.get_full_name}}</a></li>
          <li>Дата публикации: {{post.pub_date|date:"d E Y" }}</li>
        </ul>
        <br>
        {{post.text|linebreaksbr}}
			
    </p>
	<hr>
  {%endfor%}
  {% include 'posts/includes/paginator.html' with page=page_obj %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}

    {% for post in page_obj %}
        <h3>
            Автор:<a href="{% url 'posts:profile' username=post.author.username %}">{{ post.author.get_full_name }}</a>, Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </h3>
        <p>{{ post.text|linebreaksbr }}</p>
        {% if post.group %}
            <p><a href="{% url 'posts:group_list' slug=post.group.slug %}">{{ post.group }}</a></p>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' with page=page_obj %}
{% endblock %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %} Пост {{ posts|truncatechars:30 }} {% endblock %}
{% block content %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ posts.pub_date|date:"d F Y" }}
        </li>
        {% if posts.group %}  
        <li class="list-group-item">
          Группа: {{ posts.group }}
          <a href="{% url 'posts:group_list' posts.group.slug %}">
            все записи группы {{ posts.group.title }}
          </a>
        </li>
        {% endif %}

        <li class="list-group-item">
          Автор: {{posts.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span> {{ quantity }} </span>
        </li>
        <li class="list-group-item  ">
          <a href="{% url 'posts:profile' posts.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ posts.text }}
      </p>
      {% if request.user.is_authenticated %}

      <a class="btn btn-primary" href="{% url 'posts:post_edit' posts.id %}">
        Редактировать запись
      </a>
      {% endif %}
    </article>
  </div> 
</main>
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% include 'includes/header.html' %}
{% block title %} Профайл пользователя {{ author.username }} {% endblock %}
{% block content%}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.username }} </h1>
        <h3>Всего постов: {{ quantity }} </h3>   
        <article>
        {% for posts in page_obj %}
          <ul>
            <li>
              Автор: {{ posts.author.get_full_name }}
            <a href="{% url 'posts:profile' author.username %}">
              все посты пользователя
            </a>
            </li>
            <li>
              Дата публикации: {{ posts.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ posts.text|linebreaksbr }}
          </p>
          <a href="{% url 'posts:post_detail' post_id=posts.id %}">
            Перейти в постик
          </a>
          <br>
        </article>
        <p>
        {% if posts.group %}
          <p>
          <a href="{% url 'posts:group_list' posts.group.slug %}">
            все записи группы
          </a>
        {% endif %}
          </p>
        <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' with page=page_obj %}
      </div>
{% endblock %}